INSERT INTO [dbo].[PRODUTOS]
(
	[CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PREÇO DE LISTA]
)
VALUES
(
	'1040107', 'LIGHT - 350ML - MELANCIA', 'LATA', '350ML', 'MELANCIA', 4.56
)

INSERT INTO [dbo].[VENDEDORES] 
(
	[MATRICULA], [NOME], [PERCENTUAL COMISSAO]
)
VALUES
(
	'00233', 'José Geraldo da Fonseca', 0.1
)