INSERT INTO [dbo].[PRODUTOS](
	[CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PREÇO DE LISTA]
)
VALUES(
	'1040107', 'LIGHT - 350ML - MELANCIA', 'LATA', '350ML', 'MELANCIA', 4.56
)

INSERT INTO [dbo].[VENDEDORES] (
	[MATRICULA], [NOME], [PERCENTUAL COMISSAO]
)
VALUES(
	'00233', 'José Geraldo da Fonseca', 0.1
)

INSERT INTO [dbo].[CLIENTES](
	[CPF],
	[NOME COMPLETO],
	[ENDERECO 1],
	[ENDERECO 2],
	[BAIRRO],
	[CIDADE],
	[ESTADO],
	[CEP],
	[DATA DE NASCIMENTO],
	[IDADE],
	[SEXO],
	[LIMITE DE CREDITO],
	[VOLUME DE COMPRA],
	[PRIMEIRA COMPRA]
)
VALUES(
	'00132485978',
	'José Ferreira',
	'Rua projetada A Nº 10',
	'',
	'Centro',
	'Rio de Janeiro',
	'RJ',
	'2000000',
	'1990-10-25',
	27,
	'M',
	120000.50,
	1000,
	1
)